version: '3.8'

services:
  app:
    container_name: avosloi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "6829:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Vérifie que default.conf existe !
    restart: always
